server:
  # tomcat:
#    max-swallow-size: 100MB
#    max-http-post-size: 100MB
#    max-threads: 200
  #    uri-encoding: UTF-8
#    max-threads: 1000
#    min-spare-threads: 30
#  tomcat:
#    max-http-post-size: 4MB
  max-http-header-size: 204800
  port: 8080
  servlet:
    context-path: /study

spring:
  kafka:
    bootstrap-servers: 192.168.30.100:9092
#    bootstrap-servers: localhost:9092
#    bootstrap-servers: 127.0.0.1:9092
#    bootstrap-servers: ti.canpoint.cn:9092（配置ti.canpoint.cn映射的ip为localhost）
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      retries: 0
      linger: 1
      batch-size: 4096
      buffer-memory: 40960
    consumer:
      group-id: test
      enable-auto-commit: true
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      