spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://39.105.162.131:13306/tiku?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=GMT%2B8
      username: root
      password: mysql@canpoint.com
#      url: jdbc:mysql://localhost:3307/tiku?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=GMT%2B8
#      username: root
#      password: 123456
      initial-size: 10
      max-active: 100
      min-idle: 10
      max-wait: 60000
      pool-prepared-statements: true
      max-open-prepared-statements: 20
#      max-pool-prepared-statement-per-connection-size: 20
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 120000
      #Oracle需要打开注释
      #validation-query: SELECT 1 FROM DUAL
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        #login-username: admin
        #login-password: admin
      filter:
        stat:
          log-slow-sql: true
          slow-sql-millis: 1000
          merge-sql: false
        wall:
          config:
            multi-statement-allow: true
  redis:
    #    open: false  # 是否开启redis缓存  true开启   false关闭
    open: true  # 是否开启redis缓存  true开启   false关闭
    database: 0
    host: 39.105.162.131
    port: 9381
    #  password:    # 密码（默认为空）
    password: Can&*^Edadpoin1t   # 密码
    timeout: 6000ms  # 连接超时时长（毫秒）
    jedis:
      pool:
        max-active: 1000  # 连接池最大连接数（使用负值表示没有限制）
        max-wait: -1ms      # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 10      # 连接池中的最大空闲连接
        min-idle: 5       # 连接池中的最小空闲连接
  profiles:
    active: dev


##多数据源的配置
dynamic:
  datasource:
    slave1:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://39.105.162.131:13306/tiku_pre?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=GMT%2B8
      username: root
      password: mysql@canpoint.com
      initial-size: 10
      max-active: 100
      min-idle: 10
      max-wait: 60000
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      #Oracle需要打开注释
      #validation-query: SELECT 1 FROM DUAL
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        #login-username: admin
        #login-password: admin
      filter:
        stat:
          log-slow-sql: true
          slow-sql-millis: 1000
          merge-sql: false
        wall:
          config:
            multi-statement-allow: true
    slave2:
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://39.105.162.131:13306/tiku_produced?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=GMT%2B8
          username: root
          password: mysql@canpoint.com
          initial-size: 10
          max-active: 100
          min-idle: 10
          max-wait: 60000
          pool-prepared-statements: true
          max-pool-prepared-statement-per-connection-size: 20
          time-between-eviction-runs-millis: 60000
          min-evictable-idle-time-millis: 300000
          #Oracle需要打开注释
          #validation-query: SELECT 1 FROM DUAL
          test-while-idle: true
          test-on-borrow: false
          test-on-return: false
          stat-view-servlet:
            enabled: true
            url-pattern: /druid/*
            #login-username: admin
            #login-password: admin
          filter:
            stat:
              log-slow-sql: true
              slow-sql-millis: 1000
              merge-sql: false
            wall:
              config:
                multi-statement-allow: true
    slave3:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://39.105.162.131:13306/tiku_books?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=GMT%2B8
      username: root
      password: mysql@canpoint.com
      initial-size: 10
      max-active: 100
      min-idle: 10
      max-wait: 60000
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      #Oracle需要打开注释
      #validation-query: SELECT 1 FROM DUAL
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        #login-username: admin
        #login-password: admin
      filter:
        stat:
          log-slow-sql: true
          slow-sql-millis: 1000
          merge-sql: false
        wall:
          config:
            multi-statement-allow: true
    slave4:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://39.105.162.131:13306/baidu_call_back?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=GMT%2B8
      username: root
      password: mysql@canpoint.com
      initial-size: 10
      max-active: 100
      min-idle: 10
      max-wait: 60000
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      #Oracle需要打开注释
      #validation-query: SELECT 1 FROM DUAL
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        #login-username: admin
        #login-password: admin
      filter:
        stat:
          log-slow-sql: true
          slow-sql-millis: 1000
          merge-sql: false
        wall:
          config:
            multi-statement-allow: true
    common:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://39.105.162.131:13306/tiku_common?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=GMT%2B8
      username: root
      password: mysql@canpoint.com
      initial-size: 10
      max-active: 100
      min-idle: 10
      max-wait: 60000
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      #Oracle需要打开注释
      #validation-query: SELECT 1 FROM DUAL
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        #login-username: admin
        #login-password: admin
      filter:
        stat:
          log-slow-sql: true
          slow-sql-millis: 1000
          merge-sql: false
        wall:
          config:
            multi-statement-allow: true
#    slave2:
#      driver-class-name: org.postgresql.Driver
#      url: jdbc:postgresql://localhost:5432/education_platform
#      username: cpcampus
#      password: cpcampus
#    slave3:
#      driver-class-name: com.mysql.cj.jdbc.Driver
#      url: jdbc:mysql://112.126.73.185:3306/education_platform?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=GMT%2B8
#      username: cpcampus
#      password: cpcampus


pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql

#搜索引擎配置
elasticsearch:
#多个node用逗号隔开
  clusterNodes: 39.105.162.131:9920

#阿里云OSS配置
oss:
  endpoint: oss-cn-beijing.aliyuncs.com
  url: http://qp-tiku-test.oss-cn-beijing.aliyuncs.com
  accessKeyId: TZC68mOapnQ8cwUM
  secretAccessKey: 1wfN8235HQ2eLnCa5s9kZyG4nQcxBP
  bucketName: qp-tiku-test

#网关域名
apigateway-domain :
#  defaultName : http://39.105.153.115:9001
  defaultName : http://api.canpoint.cn:9001

apigateway :
  accessKeyID: c0e72768-b32c-4dd4-b7b8-6720c9ab1532
  accessKeySecret: f1f2dd74-7678-490d-bd34-2cab88721394
  appKey: d03a9d03d4cf63ba6a618490bf96b3e1
  appSecret: bd9d99bdb7ceb69a8dff3223743a7b25
  originIp: 39.105.162.131

#网关接口配置文件
apiconstant-config:
  name: apiConstantDev.properties

cronjobs:
  open: false # 是否执行定时任务  true开启   false关闭
  poolSize: 5
autosplit:
  open: false # 是否启用自动拆题  true开启   false关闭

#试题结构标记图片
question-structure:
  imgPath: http://itembank-factory-console.canpoint.cn/tools/img/edit/

#文本相似度
text-sim:
  url: http://47.97.20.153/search/api